"""
Django settings for dj_pro project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APPS_DIR = os.path.join(BASE_DIR,'dj_pro/apps')
BASE_ROOT =Path(__file__).resolve().parent

sys.path.append(BASE_DIR)
sys.path.append(APPS_DIR)



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l4lqnx8k1^+te)(c-c)f&+7i@&)kfoctfytu$7xb!5&9^89rf+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',

    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # app 注册
    'user',
    'home',
    'book',
    'oldbook',
    # rest_framework 注册
    'rest_framework',
    # 跨域问题
    'corsheaders',
    # djang过滤
    'django_filters',
    # jwt 认证
    'jwt',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 跨域问题中间件
    'corsheaders.middleware.CorsMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'dj_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dj_pro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mqbookstore',
                'USER':'wangmengqi',
                'PASSWORD':'wangmengqi123',
                'HOST':'127.0.0.1',
                'PORT':3306,
                'CHARSET':'utf8',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False




STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,STATIC_URL)
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_ROOT,'media')
# print(MEDIA_ROOT)

# print(MEDIA_ROOT)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 用户自定义表注册
AUTH_USER_MODEL = 'user.UserInfo'


# 跨域问题注册
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)
CORS_ALLOW_HEADERS = (
    'authorization',
    'content-type',
)


# rest_framework 注册
REST_FRAMEWORK = {

'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

'PAGE_SIZE': 3,

}

# jwt 配置过期时间
import datetime
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
}
DJ_URL = '127.0.0.1:8000'
VUE_URL = 'http://localhost:8080/'


NOTIFY_URL = DJ_URL + 'book/success'
NOTIFY_URL_O = DJ_URL + 'oldbook/success'

RETURN_URL = VUE_URL + '/success'
RETURN_URL_O = VUE_URL + '/success2'

# RETURN_URL = 'https://www.baidu.com'