# Generated by Django 3.2.4 on 2022-03-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页轮播图表', 'verbose_name_plural': '首页轮播图表'},
        ),
    ]
