# Generated by Django 3.2.4 on 2022-03-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OldBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='书名')),
                ('simple_introduce', models.CharField(max_length=64, verbose_name='简介')),
                ('price', models.CharField(max_length=12, verbose_name='价格')),
                ('is_sell', models.BooleanField(default=False, verbose_name='是否卖出')),
                ('image', models.ImageField(blank=True, null=True, upload_to='old_book', verbose_name='书的图片')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('buy_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_user', to=settings.AUTH_USER_MODEL, verbose_name='买到书的人')),
                ('sell_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sell_user', to=settings.AUTH_USER_MODEL, verbose_name='卖书的人')),
            ],
        ),
    ]
