# Generated by Django 3.2.4 on 2022-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldbook', '0004_auto_20220319_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldbook',
            name='image',
            field=models.ImageField(blank=True, default='old_book/3e2c4d4f20c0113f68b826bd3cbf55a4_L9N5DNc.jpeg', null=True, upload_to='old_book', verbose_name='书的图片'),
        ),
    ]
