# Generated by Django 4.0 on 2021-12-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('publisher', models.CharField(max_length=32, verbose_name='出版社')),
                ('image', models.ImageField(default='book/default.jpg', upload_to='book', verbose_name='书的图片')),
                ('author', models.CharField(max_length=32, null=True, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32, verbose_name='分类名')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时期')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='图书')),
            ],
        ),
    ]
