# Generated by Django 3.2.4 on 2021-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num',
            field=models.CharField(default='1001', max_length=64, verbose_name='订单号'),
        ),
    ]
