# Generated by Django 3.2.4 on 2022-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='无', max_length=32, verbose_name='出版社'),
        ),
    ]
